const SignupMessage: { [key: string]: string } = Object.freeze({
    title: "یک حساب کاربری جدید بسازید!",
    existAccount: "از قبل حساب کاربری دارید؟",
    login: "وارد شوید.",
    firstname: "نام",
    firstnameMin: "نام را وارد نمایید.",
    firstnameMax: "نام نباید بیشتر از ۲۰ کاراکتر باشد.",
    lastname: "نام خانوادگی",
    lastnameMin: "نام خانوادگی را وارد نمایید.",
    lastnameMax: "نام خانوادگی نباید بیشتر از ۲۰ کاراکتر باشد.",
    email: "پست الکترونیکی",
    emailMin: "پست الکترونیکی را وارد نمایید.",
    emailMax: "پست الکترونیکی نباید بیشتر از ۵۰ کاراکتر باشد.",
    emailValidation: "پست الکترونیکی معتبر نمی‌باشد",
    mobile: "تلفن همراه",
    mobileMin: "شماره تلفن همراه را وارد نمایید.",
    mobileMax: "شماره موبایل معتبر نمی‌باشد.",
    mobileValidation: "شماره موبایل معتبر نمی‌باشد.",
    password: "گذرواژه",
    passwordMin: "گذرواژه باید حداقل ۶ کاراکتر باشد.",
    paswordMax: "گذرواژه نباید بیشتر از ۲۰ کاراکتر باشد.",
    passwordValidation: "گذرواژه باید شامل یکی از علامت های (^*&%$#@!) باشد",
    rePassword: "تکرار گذرواژه",
    rePasswordMin: "تکرار گذرواژه را وارد نمایید.",
    rePasswordMax: "تکرار گذرواژه نباید بیشتر از ۲۰ کاراکتر باشد.",
    rePasswordValidation: "گذرواژه و تکرار آن یکسان نیستند.",
    submit: "ثبت نام"
});

export default SignupMessage;