import type { Metadata } from "next";
import localFont from "next/font/local";
import { Toaster } from "@/components/ui/sonner";
import TopProgressBar from "@/components/ui/topProgressBar";
import axios from "axios";
import { setupInterceptorsTo } from "@/lib/axiosInstance";
import "./globals.css";
import ReactQueryProvider from "@/lib/reactQueryProvider";

setupInterceptorsTo(axios);

const IRANSansX = localFont({
  src: [
    {
      path: "../public/fonts/IRANSansX-Regular.woff",
      weight: "400",
      style: "normal"
    },
    {
      path: "../public/fonts/IRANSansX-Bold.woff",
      weight: "700",
      style: "normal"
    }
  ],
  variable: "--font-IRANSansX"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa-IR" dir="rtl">
      <body>
        <TopProgressBar />
        <ReactQueryProvider>
          <main className={IRANSansX.className}>{children}</main>
        </ReactQueryProvider>
        <Toaster className="!font-IRANSansX" position="top-left" richColors />
      </body>
    </html>
  );
}
