import type { Metadata } from "next";
import localFont from "next/font/local";
import { Toaster } from "@/components/ui/sonner";
import TopProgressBar from "@/components/ui/topProgressBar";
import { ThemeProvider } from "@/providers/ThemeProvider";
import axios from "axios";
import { setupInterceptorsTo } from "@/lib/axios";
import ReactQueryProvider from "@/providers/QueryProvider";
import "@/styles/globals.css";
import "@/styles/nprogress.css";

setupInterceptorsTo(axios);

const IRANSansX = localFont({
  src: [
    {
      path: "../public/fonts/IRANSansX-Regular.woff",
      weight: "400",
      style: "normal"
    },
    {
      path: "../public/fonts/IRANSansX-Bold.woff",
      weight: "700",
      style: "normal"
    }
  ],
  variable: "--font-IRANSansX"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa-IR" dir="rtl" suppressHydrationWarning>
      <body>
        <ReactQueryProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <TopProgressBar />
            <main className={IRANSansX.className}>{children}</main>
            <Toaster
              className="!font-IRANSansX"
              position="top-left"
              richColors
            />
          </ThemeProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
