import type { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
  title: "ورود",
  description: "Generated by create next app"
};

export default function LoginLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="w-4/5 md:w-5/12 flex flex-col">{children}</div>
  );
}
